### ISSUE TITLE
Enhanced AI + IronLadders 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [0Templ/IronLadders#1]
Minecraft 1.19.2
Forge 43.3.5

EnhancedAI-1.8.5-mc1.19.2.jar
ironladders-1.19.2-1.0.0-forge.jar
neruina-1.3.0-forge+1.18.2-1.20.1.jar

I noticed a feature that in combination with this [Enhanced AI], mobs cannot use these ladders, although this is part of the function of another mod, but I do not know which mod needs an update to make it work together. There are also some errors in the log, I threw it below.

Also, it is not the ruin that considers the copper staircase to be strongly ticking. Maybe it will help you:

- neruina-1.3.0-forge+1.18.2-1.20.1.jar
- spark-1.10.37-forge.jar
- observable-3.3.1.jar

![2024-02-28_21 33 20](https://github.com/0Templ/IronLadders/assets/106809386/c78acfbd-dc72-4fa8-8c78-9c51325e71d5)

https://www.curseforge.com/minecraft/mc-mods/enhanced-ai
![image](https://github.com/0Templ/IronLadders/assets/106809386/2a399294-b765-40ed-9ddd-b3e67d66b6ce)

> [28Feb2024 21:27:56.335] [Worker-ResourceReload-8/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file minecraft:gold_nugget_from_blasting from minecraft:recipes/gold_nugget_from_blasting.json
> com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:512) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:549) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
> Caused by: java.io.EOFException: End of input at line 1 column 1 path $
> 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar%2394!/:?]
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:510) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	... 11 more
> [28Feb2024 21:27:56.375] [Worker-ResourceReload-8/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file minecraft:iron_nugget_from_blasting from minecraft:recipes/iron_nugget_from_blasting.json
> com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:512) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:549) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
> Caused by: java.io.EOFException: End of input at line 1 column 1 path $
> 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar%2394!/:?]
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:510) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	... 11 more
> [28Feb2024 21:27:56.870] [Worker-ResourceReload-0/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file minecraft:gold_nugget_from_blasting from minecraft:recipes/gold_nugget_from_blasting.json
> com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:512) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:549) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
> Caused by: java.io.EOFException: End of input at line 1 column 1 path $
> 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar%2394!/:?]
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:510) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	... 11 more
> [28Feb2024 21:27:56.893] [Worker-ResourceReload-0/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file minecraft:iron_nugget_from_blasting from minecraft:recipes/iron_nugget_from_blasting.json
> com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:512) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:549) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
> Caused by: java.io.EOFException: End of input at line 1 column 1 path $
> 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%2394!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar%2394!/:?]
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:510) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
> 	... 11 more
>

**Comment by 0Templ** [comment]
Thanks for finding the issue with the copper ladders! Fixed it in version 1.0.1. 

About compatibility with the EnhancedAI:
Checked the behaviour of mobs with Iron ladders and found no serious differences from their behaviour with normal ladders, but vanilla ai does not calculate acceleration from ladders when calculating the movements of the creature. In future versions I will add the ability to disable accelerated climbing for different creatures

I'm not sure if the errors in the log that you threw are related to Iron Ladders, as I was not able to repeat such an error on this version of forge. Maybe some of the other mods use too old version of forge.

**Comment by 0Templ** [comment]
Thanks for finding the copper ladders bug! Fixed in 1.0.1.

About compatibility with mod EnhancedAI:
Tested the behaviour of mobs with Iron ladders and found no major differences from their behaviour with normal ladders, but vanilla ai does not calculate acceleration from ladders when calculating creature movements. In future versions I will add the ability to disable accelerated climbing for different creatures

I'm not sure if the errors in the log that you threw are related to Iron Ladders, as I was not able to repeat such an error on this version of forge. Maybe some of the other mods use too old version of forge.
