### ISSUE TITLE
ResourceReload

### ISSUE THREAD

**Issue by Krimatoria** [0Templ/IronLadders#2]
the problem persists in the new update 
ironladders-1.20.1-2.1.12-forge.jar

> [02Mar2024 19:28:10.149] [Worker-ResourceReload-4/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file minecraft:iron_nugget_from_blasting from minecraft:recipes/iron_nugget_from_blasting.json
> com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:526) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_278771_(SimpleJsonResourceReloadListener.java:41) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:17) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
> Caused by: java.io.EOFException: End of input at line 1 column 1 path $
> 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1455) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:558) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:769) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar%2372!/:?]
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	... 13 more
> [02Mar2024 19:28:10.214] [Worker-ResourceReload-5/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file endlessbiomes:chests/get_shared_pain from endlessbiomes:loot_tables/chests/get_shared_pain.json
> com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 19 column 14 path $.pools[0].entries[0].functions[1]
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:526) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_278771_(SimpleJsonResourceReloadListener.java:41) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.LootDataManager.m_278660_(LootDataManager.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
> Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 19 column 14 path $.pools[0].entries[0].functions[1]
> 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:485) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:422) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:779) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar%2372!/:?]
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	... 11 more
> [02Mar2024 19:28:10.280] [Worker-ResourceReload-6/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file minecraft:gold_nugget_from_blasting from minecraft:recipes/gold_nugget_from_blasting.json
> com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:526) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_278771_(SimpleJsonResourceReloadListener.java:41) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:17) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
> Caused by: java.io.EOFException: End of input at line 1 column 1 path $
> 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1455) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:558) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:769) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar%2372!/:?]
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	... 13 more
> [02Mar2024 19:28:10.316] [Worker-ResourceReload-6/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file minecraft:iron_nugget_from_blasting from minecraft:recipes/iron_nugget_from_blasting.json
> com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:526) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_278771_(SimpleJsonResourceReloadListener.java:41) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:17) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
> Caused by: java.io.EOFException: End of input at line 1 column 1 path $
> 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1455) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:558) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:769) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar%2372!/:?]
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	... 13 more
> [02Mar2024 19:28:11.258] [Worker-ResourceReload-5/ERROR] [net.minecraftforge.common.ForgeHooks/]: Couldn't parse element loot_tables:ancient_aether:chests/sentry_laboratory_loot
> com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'ancient_aether:crystal_aercloud'
> 	at net.minecraft.util.GsonHelper.m_13866_(GsonHelper.java:145) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
> 	at net.minecraft.util.GsonHelper.m_13874_(GsonHelper.java:145) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.util.GsonHelper.m_13909_(GsonHelper.java:153) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:55) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:40) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2372!/:?]
> 	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:471) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:192) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2372!/:?]
> 	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:481) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:294) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:291) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar%2372!/:?]
> 	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:871) ~[forge-1.20.1-47.2.6-universal.jar%23737!/:?]
> 	at net.minecraftforge.common.ForgeHooks.lambda$getLootTableDeserializer$3(ForgeHooks.java:848) ~[forge-1.20.1-47.2.6-universal.jar%23737!/:?]
> 	at net.minecraft.world.level.storage.loot.LootDataType.deserialize(LootDataType.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$4(LootDataManager.java:56) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
> 	at net.minecraft.world.level.storage.loot.LootDataManager.m_278660_(LootDataManager.java:55) ~[client-1.20.1-20230612.114412-srg.jar%23732!/:?]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
>

**Comment by 0Templ** [comment]
Strange, I tried running Iron Ladders with large Mod Packs and no conflicts with other mods. Perhaps this error is caused by the mod Endless Biomes and its error with loot tables (Couldn't parse data file endlessbiomes:chests/get_shared_pain from endlessbiomes:loot_tables/chests/get_shared_pain.json). Is this error present if you remove Iron Ladders or 
Endless Biomes?

**Comment by Krimatoria** [comment]
> Strange, I tried running Iron Ladders with large Mod Packs and no conflicts with other mods. Perhaps this error is caused by the mod Endless Biomes and its error with loot tables (Couldn't parse data file endlessbiomes:chests/get_shared_pain from endlessbiomes:loot_tables/chests/get_shared_pain.json). Is this error present if you remove Iron Ladders or Endless Biomes?

@Xelbayria - Do you know what it could be? I just remember that you seem to be good at chests)))

**Comment by Krimatoria** [comment]
I removed the bios to check it, but this error is no longer there, it has changed and now it looks like this.
Biomes have another problem, I reported it to Discord since they are not on GitHub.

**Comment by Krimatoria** [comment]
Here are the last errors that were in my blog, they no longer contain that error with the chest at EndlessBiomes. Maybe something fixed it, but now the error looks different. I don't know if this will help or not.

I'm going to bed) good night)

[Ladders.txt](https://github.com/0Templ/IronLadders/files/14475604/Ladders.txt)

**Comment by Xelbayria** [comment]
> Here are the last errors that were in my blog, they no longer contain that error with the chest at EndlessBiomes. Maybe something fixed it, but now the error looks different. I don't know if this will help or not.
> 
> I'm going to bed) good night)
> 
> [Ladders.txt](https://github.com/0Templ/IronLadders/files/14475604/Ladders.txt)

From the log you provided ☝️ 
there is a problem with JSON files via recipes. it couldn't be parsed. One could use JSON validator to make sure it's the ID of these items and all correct. 

Good luck

**Comment by Krimatoria** [comment]
> JSON validator



> > Here are the last errors that were in my blog, they no longer contain that error with the chest at EndlessBiomes. Maybe something fixed it, but now the error looks different. I don't know if this will help or not.
> > I'm going to bed) good night)
> > [Ladders.txt](https://github.com/0Templ/IronLadders/files/14475604/Ladders.txt)
> 
> From the log you provided ☝️ there is a problem with JSON files via recipes. it couldn't be parsed. One could use JSON validator to make sure it's the ID of these items and all correct.
> 
> Good luck

https://jsonlint.com/
I just uploaded ironladders-common.toml there
![image](https://github.com/0Templ/IronLadders/assets/106809386/29032bd3-a9d7-4503-bb77-fba8dbd6516b)

**Comment by Xelbayria** [comment]
wait wait. 
TOML and JSON are not the same thing. 😓  That TOML file is just settings for the mod. you just need to check the recipe files and look at the IDs of the items. if they are all correct, then you can drag one of these recipe files to JSONLint and ensure they are all good.

**Comment by Krimatoria** [comment]
> wait wait. TOML and JSON are not the same thing. 😓 That TOML file is just settings for the mod. you just need to check the recipe files and look at the IDs of the items. if they are all correct, then you can drag one of these recipe files to JSONLint and ensure they are all good.

Yes, I noticed it later))) I downloaded it wrong) Well, I think the developer can check it himself) since JSON files are already in mod, they are not in the config.

**Comment by 0Templ** [comment]
In the comments on the Endless Bioms mod page write about a similar problem and apparently the author has already fixed it.
