### ISSUE TITLE
1.20.1 Data file minecraft:iron_nugget

### ISSUE THREAD

**Issue by Krimatoria** [0Templ/IronLadders#5]
Forge 47.3.5 
1.20.1 

ironladders-1.20.1-2.2.3-forge.jar

If it's related to another mod since I have an assembly, I'll try to find a match.

> [22:30:18] [Worker-ResourceReload-5/ERROR]: Couldn't parse data file minecraft:iron_nugget_from_blasting from minecraft:recipes/iron_nugget_from_blasting.json
> --
> 9398 | com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
> 9399 | at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:526) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9400 | at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9401 | at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9402 | at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_278771_(SimpleJsonResourceReloadListener.java:41) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9403 | at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9404 | at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:17) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9405 | at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9406 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
> 9407 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
> 9408 | at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
> 9409 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
> 9410 | at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
> 9411 | at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
> 9412 | at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
> 9413 | Caused by: java.io.EOFException: End of input at line 1 column 1 path $
> 9414 | at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1455) ~[gson-2.10.jar%23107!/:?]
> 9415 | at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:558) ~[gson-2.10.jar%23107!/:?]
> 9416 | at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.jar%23107!/:?]
> 9417 | at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:769) ~[gson-2.10.jar%23107!/:?]
> 9418 | at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar%23107!/:?]
> 9419 | at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar%23107!/:?]
> 9420 | at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9421 | ... 13 more
> 
> 
> [22:30:17] [Worker-ResourceReload-2/ERROR]: Couldn't parse data file minecraft:iron_nugget_from_blasting from minecraft:recipes/iron_nugget_from_blasting.json
> --
> 9190 | com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
> 9191 | at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:526) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9192 | at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9193 | at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9194 | at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_278771_(SimpleJsonResourceReloadListener.java:41) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9195 | at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9196 | at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:17) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9197 | at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9198 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
> 9199 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
> 9200 | at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
> 9201 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
> 9202 | at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
> 9203 | at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
> 9204 | at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
> 9205 | Caused by: java.io.EOFException: End of input at line 1 column 1 path $
> 9206 | at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1455) ~[gson-2.10.jar%23107!/:?]
> 9207 | at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:558) ~[gson-2.10.jar%23107!/:?]
> 9208 | at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.jar%23107!/:?]
> 9209 | at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:769) ~[gson-2.10.jar%23107!/:?]
> 9210 | at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar%23107!/:?]
> 9211 | at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar%23107!/:?]
> 9212 | at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%23796!/:?]
> 9213 | ... 13 more
>

**Comment by 0Templ** [comment]
I don't see a connection with Iron Ladders. If the issue disappears when the mod is removed from the folder, please let me know.

**Comment by Krimatoria** [comment]
> I don't see a connection with Iron Ladders. If the issue disappears when the mod is removed from the folder, please let me know.

I'll check it out today
