### ISSUE TITLE
Empty tags error in recipies shown in JEI, REI, etc.

### ISSUE THREAD

**Issue by ExiledMiner04** [0Templ/IronLadders#6]
![image](https://github.com/user-attachments/assets/21488d3e-3d7d-496c-916f-cc285355f4cd)

Not one material is recognized, and I have proper mods that provide said materials.

Mods that provide said oredict ores:

vanilla Minecraft
All The Ores
Basic Nether Ores 
Basic End Ores

I'm using neoforge 1.21.1 version 21.1.31

**Comment by ExiledMiner04** [comment]
https://gist.github.com/ExiledMiner04/0a13f78fd31c5fd9ec0d80d20d186a8a
Use the new C tags to fix the missing material tags  for neoforge versions of the mod.

**Comment by 0Templ** [comment]
Fixed in [2.5.12](https://legacy.curseforge.com/minecraft/mc-mods/iron-ladders/files/5743363).
 Thanks for the report!
